container:
  image: archlinux:latest
  cpu: 2
  memory: 2G

task:
  script:
    - pacman -Syu --noconfirm
    - pacman -Fy
    - echo 'en_US.UTF-8 UTF-8' >> /etc/locale.gen
    - echo 'LANG=en_US.UTF-8' > /etc/locale.conf        
    - locale-gen
    - timedatectl set-timezone America/Sao_Paulo
    - pacman-key --init
    - pacman -Syu git mdbook
    - git clone https://github.com/kassius-publishing/introducao_a_programacao_em_python-pt-br.git
    - mdbook clean
    - mdbook build
