container:
  image: openjdk:latest
  cpu: 2
  memory: 2G

task:
  script:
    - sudo pacman -Syu --noconfirm
    - pacman -Fy
    - echo 'en_US.UTF-8 UTF-8' >> /etc/locale.gen
    - echo 'LANG=en_US.UTF-8' > /etc/locale.conf        
    - locale-gen
    - timedatectl set-timezone America/Sao_Paulo
    - sudo pacman-key --init
    - sudo pacman -Syu git mdbook
